[server]
host = "localhost"
port = 80

[database]
user = "postgres"
password = "postgres"
host = "localhost"
port = 5432
db = "postgres"

[https]
cert = "../../../me/perms/ca.crt" # 证书路径
pkey = "../../../me/perms/tls.key" # 私钥路径
