[server]
host = "localhost"
port = 80
basic_auth = {} # { foo = "bar", ... }

[database]
user = "postgres"
password = "postgres"
host = "localhost"
port = 5432
db = "postgres"

[https]
cert = "" # 证书路径
pkey = "" # 私钥路径
